- src/hexo/themes/documentation/layout/partials/header.hbs
@molant this will fix one of the search input a11y warnings we get. 
Added label for the search documentation input but am visually hiding it.
> add label for search input

- helpers/updater.js
Use Regex to split the content and separate frontmatter from the rest of the file. This way the page won't break if the page is generated multiple times.
> Fix contributor page

- src/hexo/themes/documentation/layout/changelog.hbs
Scripts were missing in the changelog page.
This PR is created separately so that it could be merged earlier.
> Fix: Fix nav and search in changelog page

- helpers/updater.js
- src/hexo/source/404.md
- src/hexo/source/_data/menu.yml
- src/hexo/source/about.md
- src/hexo/source/contributors.md
- src/hexo/themes/sonarwhal/helper/index.js
- src/hexo/themes/sonarwhal/layout/partials/contributors.hbs
- src/hexo/themes/sonarwhal/layout/partials/sub-page.hbs
- src/hexo/themes/sonarwhal/scripts/link-filter.js
- src/hexo/themes/sonarwhal/source/js/scanner-submit.js
- web.config
Make sure you:
Fix #229
1. In `updater`,  permalinks are changed from `/about/faq.html` to `/about/faq/index.html`. This tells hexo to render `faq.md` into its own folder and both  `about/faq` ,  `about/faq/` work as functional urls yet `index.html` doesn't show in the address bar.
2. Add helper so that `index.html` is omitted when `permalink` is cited anywhere in the templated.
3. Edit hexo filter `link-filter` so that it takes into account the fact that an extra directory level is added to the current page.
> Chore: normalize urls in public site

- src/hexo/themes/sonarwhal/helper/index.js
Make sure you:
In production `https://sonarwhal.com/dist/docs/user-guide/rules` gets redirected to `https://sonarwhal.com/dist/docs/user-guide/rules/`, which returns 404. So the treeview is broken. Fix the links in treeview to all have `/` at the end of the links. But [this setting](https://github.com/sonarwhal/sonarwhal.com/blob/d7873ef9fb3ca184f30debc5b17593d35a757bc7/web.config#L69) in web.config might need to be changed so urls still work without slash. I'm not sure why the requests only  get redirected when there is no `/` at the end. @molant
> Fix: fix treeview links in production

- src/hexo/themes/sonarwhal/source/core/css/scan-results.css
Make sure you:
The close icon '-' for the close details button the scan results page was rendering
too close to the 'close' text in some browsers.
Fix #313
> Fix: Proximity of close details icon on scan results page

- .gitignore
- _config.yml
- gulpfile.js
Make sure you:
Fix #377
* Move images in gulp task
* Update images links in .md files
* Hexo builds from the md files with updated image links
https://github.com/sonarwhal/sonarwhal/pull/794 has to be merged first so that the `revreplace` works int he markdown files.
> Fix: Copy markdown images in the gulp task

- src/sonarwhal-theme/source/core/css/base.css
Make sure you:
Add CSS to add a margin above the first details element after
a heading or a paragraph.
Fix #371
Close #371
> Fix: Spacing between details and headings

- src/sonarwhal-theme/helper/index.js
- src/sonarwhal-theme/layout/partials/scan-result-item.hbs
- src/sonarwhal-theme/layout/scan.hbs
> Fix: Make links to "more information" in Vulnerable JS audit clickable

- web.config
> Fix: Add trailing `/` if missing

- src/webhint-theme/source/core/css/controls.css
- src/webhint-theme/source/core/css/navigation.css
Make sure you:
The recent changes to the header cause an issue with the nav item hover on secondary pages. The grey hover overflows and shows grey on the white background. 
This fixes that. @alrra @sarvaje can either of you take a look at this.
> Fix nav item header height bug

- helpers/updater.js
> Fix: Hints within a multi-hint should not appear in the ToC

- .travis.yml
- gulpfile.js
- package-lock.json
- package.json
Make sure you:
Change dependency to `gulp-zopfli-node` so pre-compiled binaries are
downloaded.
Under the hood I created a couple new packages:
* [zopfli-node](https://github.com/molant/node-zopfli): based on the latest code from [`node-zopfli`](https://npmjs.com/package/node-zopfli) but with all dependencies updated, migrated to Azure Pipelines and with autoreleases to GitHub so there are no more issues downloading the precompiled binaries
* [gulp-zopfli-node](https://github.com/molant/gulp-zopfli-node): based on the latest code from [`gulp-zopfli`](https://npmjs.com/package/gulp-zopfli) but with all dependencies updated and using `zopfli-node` instead of `node-zopfli`
I look into [`gulp-zopfli-green`](https://www.npmjs.com/package/gulp-zopfli-green) but it takes a really, really, …
> Fix: Issues with node-zopfli

- src/webhint-theme/source/core/css/home.css
Make sure you:
Staging site showing this section became uncentered: 
This PR fixes that.
> Re-center text on homepage

- src/webhint-theme/source/core/css/navigation.css
Make sure you:
Non-link text in the OpenJSF header outside of the home page need to be explicitly set to white
> Fix: OpenJSF header text color

- src/webhint-theme/scripts/custom-renderer.js
Make sure you:
Fixes bug in hexo link renderer.
Before this commit, `title` was being added to each link as `null`.
Most links in webhint docs do not have title.
When these markdown docs are getting converted to html by `hexo`, `title="null"` is getting embedded in all links. And on hover, null is shown as tooltip. This doesn't look good. See below:
After fix:
> Fix: Add `title` to html links, only if it is present in docs

- src/webhint-theme/source/core/css/layouts.css
Make sure you:
Fixes #686 
There were some commas missing, therefore the styles weren't cascading
properly.
> Fix: #686 Documentation layout bug

- src/webhint-theme/source/core/css/about.css
- src/webhint-theme/source/core/css/footer.css
- src/webhint-theme/source/core/css/navigation.css
- src/webhint-theme/source/core/css/table-of-contents.css
Make sure you:
Fix #657
Fixes capitalization in the navigation, footer, changelog (date) and table of contents.
> Fix: Capitalized letters in nav, footer and ToC

- helpers/update-site/documentation.js
- package-lock.json
- package.json
> Fix: Changelog

- helpers/update-site/documentation.js
Now appears under "Extensions" instead of "Vscodes".
- - - - - - - - - -
Fix webhintio/hint#2929
Make sure you:
> Docs: Fix category used for VS Code extension

- src/webhint-theme/layout/partials/metas.ejs
Make sure you:
Opengraph image URLs must be absolute and not relative.
This is a partial fix for #516
> prepend opengraph image URLS with https://webhint.io

- src/webhint-theme/layout/partials/styles.ejs
- src/webhint-theme/source/core/css/fonts.css
Make sure you:
- Preload to make fonts fetch and render faster
- Uses `font-display: swap` to get rid of FOIT
Before this change, in chrome with cache disabled and Slow 3G:
After this change, in chrome with cache disabled and Slow 3G:
> Webfont improvements

- architecture/server.md
Hi there!
I was taking a look at the repo in pair with @LeoSL and we found a typo on the documentation.
I saw that the guide to open Pull Requests mention that there should be an issue for any PR, I wonder if a typo like this would require an issue. Is it required?
Make sure you:
Fixed a typo
> Docs: Fix typo on server documentation

- azure-pipelines.yml
Make sure you:
Fix #842 
- Calls the integrated tests from azure pipeline
> call integration test from azure pipeline

- web.config
> The [`Clear-Site-Data` HTTP header's](https://w3c.github.io/webappsec-clear-site-data/#header) values "_MUST comply with the quoted-string grammar_", as defined in https://tools.ietf.org/html/rfc7230#section-3.2.6.
Fix #855.
> Update `Clear-Site-Data` value as quoted string

- web.config
Make sure you:
After fixing the `Clear-Site-Data` header issue of unquoted string values
in https://github.com/webhintio/webhint.io/pull/856, a new console error has surfaced:
While I don't believe this causes any real issues, to get rid of the console error, either:
- add `crossorigin="use-credentials"` to the manifest link relation
- only send the header in `text/html` responses to begin with.
This PR introduces the latter approach, which I think is more appropriate. The [spec says](https://w3c.github.io/webappsec-clear-site-data/) the various data types (`"cookie"`, `"storage"` etc.) are "_associated with the origin of a particular response’s url_", which I think implies that sending this header for sub-resources is unnecessary, and is the reason for this console error.
Edit: I should …
> Fix: Only send `Clear-Site-Data` for the root document (HTML)

- web.config
As mentioned in https://github.com/webhintio/hint/issues/624#issuecomment-548054372, RedBot is complaining about webhint.io not sending the `Vary` header consistently for all the representations of a resource.
Currently, the header is only being sent for `.br` and `.gz` files, thus a non-compressed representation of that resource is not eligible for varying the response (although I'm not sure when this would be the case outside of browsers not supporting gzip or brotli).
The explanation in the RedBot "hint" says:
> HTTP requires that the Vary response header be sent consistently for all responses if they change based upon different aspects of the request.
> 
> This resource has both compressed and uncompressed variants available, negotiated by the Accept-Encoding request header, but it …
> Fix: Send `Vary` header consistently.

- package.json
Make sure you:
Apparently since the update to puppeteer 5.1.0 the staging tests
are failing with an error in the `http-compression` rule.
> Fix: Downgrade puppeteer verstion to 5.0.0

- package.json
- src/server/index.js
This PR will track URLs from visits to webhint.io and also any referrers, which is contained within query param "source".
> Add telemetry for URL logging

- helpers/update-site/documentation.js
> Fix: Support mapping links to full URLs from `hint` Github repo

- src/server/index.js
Make sure you:
Most telemetry is part of the online scanner or submitted from the client,
but the `online-activity-url` event for keeping track of referring sources
relies on submitting telemetry from the express server powering the
documentation pages for webhint.io. 
Code was previously added to handle this event, but was not getting
submitted until now due to the telemetry package still needing initialized
with a `post` function.
> Chore: Init webhint.io telemetry so it submits

- package.json
- src/server/index.js
Eliminates the use of multiple packages for server-side telemetry.
Plus the `@hint/utils-telemetry` package is intended more for client-side usage.
> Chore: Always use appInsights server-side

- src/server/index.js
These are now tracked automatically at the host layer.
The node-level approach was incomplete as most static
content is served from the host layer and controlled by
the included `web.config` file instead of being passed on
to the node server.
> Chore: Stop tracking request URLs in node

- src/webhint-theme/helper/utils.js
- src/webhint-theme/layout/partials/doc.ejs
Make sure you:
Removes "Signal issue" link from documentation header.
> Removes "Signal issue" from docs

- docs/docs/user-guide/index.html
Make sure you:
The links to the VSCode and browser extension mentioned on this page are broken right now. I've fixed them:
https://webhint.io/docs/user-guide/#use-webhint-with-microsoft-visual-studio-code
> Docs: Fix broken extension links in user-guide

- src/server/index.js
Make sure you:
When running `npm start` node throws and error
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
This fixes this issue
> Fix: changing safeLoad for load in js-yaml>4
