webhintio/webhintio.github.io

- src/hexo/themes/documentation/layout/partials/footer.hbs
Update link URL to GitHub.com/sonarwhal
> Update github link URL - Fixes #149

- helpers/updater.js
- src/hexo/source/_data/contributors.yml
- src/hexo/source/_data/menu.yml
- src/hexo/source/about.md
- src/hexo/themes/documentation/helper/index.js
- src/hexo/themes/documentation/layout/index.hbs
- src/hexo/themes/documentation/layout/partials/contributors.hbs
- src/hexo/themes/documentation/source/core/css/about.css
@qzhou1607 here is the handlebars file for the new contributors page template. Right now I've got all the contributors so far listed in there.
@molant mentioned something about having a page template and iterating over the list? 
Also for now I don't have emoji contributions. I'll want to take a look at this portion at a later date in time.
> Responsive contributors page Fix #156

- package-lock.json
- package.json
- src/hexo/source/_data/changelog.yml
- src/hexo/themes/sonarwhal/layout/partials/scan-result.hbs
- src/hexo/themes/sonarwhal/layout/partials/styles.hbs
- src/hexo/themes/sonarwhal/source/core/css/scan-results.css
- src/hexo/themes/sonarwhal/source/core/css/type.css
- src/hexo/themes/sonarwhal/source/js/scanner-submit.js
Make sure you:
Fixes #230
@qzhou1607 ready for you to take over
Fixes #231 
Updates responsiveness of results container (did not get pushed on Monday evening and other issues arose this morning)
Update scan overview responsiveness & type size for smooth transition to smaller screens
> Scanner results design updates

- src/hexo/themes/sonarwhal/helper/index.js
- src/hexo/themes/sonarwhal/layout/partials/scan-result-item.hbs
Make sure you:
Fix #236
Fix #237
Fix #238
> Fix: Fix url related issues

- _config.yml
- helpers/updater.js
- package-lock.json
- package.json
- src/hexo/source/404.md
- src/hexo/source/about.md
- src/hexo/source/contributors.md
- src/hexo/source/docs/index.md
- src/hexo/themes/sonarwhal/helper/index.js
- src/hexo/themes/sonarwhal/layout/about.hbs
- src/hexo/themes/sonarwhal/layout/docs.hbs
- src/hexo/themes/sonarwhal/layout/index.hbs
- src/hexo/themes/sonarwhal/layout/partials/changelog-content.hbs
- src/hexo/themes/sonarwhal/layout/partials/contributors.hbs
- src/hexo/themes/sonarwhal/layout/partials/doc-index.hbs
- src/hexo/themes/sonarwhal/layout/partials/metas.hbs
- src/hexo/themes/sonarwhal/layout/partials/scan-result.hbs
- src/hexo/themes/sonarwhal/layout/partials/scripts.hbs
- src/hexo/themes/sonarwhal/layout/partials/search.hbs
- src/hexo/themes/sonarwhal/layout/partials/styles.hbs
- src/hexo/themes/sonarwhal/layout/scan.hbs
- src/server/routes/scanner.js
- src/server/routes/search.js
Make sure you:
Fix #222
* For rule pages, the content after `Why is this important?` is extracted and used as `description` in the meta tag.
* For other  pages, the content of title is used as `description` for now.
* Every page has a default image, but both the image or description can now be overridden by manually adding front matter in the **original** markdown file in sonar. 
* Remove some unused code.
> New: Generate open graph tags

- src/hexo/themes/sonarwhal/layout/scan.hbs
- src/hexo/themes/sonarwhal/source/js/unregister-service-worker.js
> Fix: unregister the service worker

- src/hexo/themes/sonarwhal/layout/scan.hbs
- src/hexo/themes/sonarwhal/source/js/unregister-service-worker.js
> Fix: fix console errors in the scan form page

- src/hexo/themes/sonarwhal/layout/partials/scan-result-item.hbs
- src/hexo/themes/sonarwhal/source/js/scanner-submit.js
- src/server/routes/scanner.js
Chore: Remove code to set status to error to all pending rules when the status is error
Make sure you:
> Chore: Hide code box when there is no code in the error

- src/hexo/themes/sonarwhal/layout/partials/scan-result-item.hbs
- src/hexo/themes/sonarwhal/source/js/scanner-submit.js
Code box can also contains a resource url, so now we check also if there is a resource url.
Make sure you:
> Fix: Fix code box.

- src/hexo/source/_data/changelog.yml
- src/hexo/themes/sonarwhal/layout/partials/scan-queue.hbs
- src/hexo/themes/sonarwhal/layout/partials/scan-result-item.hbs
- src/hexo/themes/sonarwhal/source/core/css/documentation.css
- src/hexo/themes/sonarwhal/source/core/css/navigation.css
- src/hexo/themes/sonarwhal/source/core/css/scan-results.css
- src/hexo/themes/sonarwhal/source/core/css/type.css
* Make documentation link in scan results more clear
* Fix URLs that break layout on smaller screens
* Fix section link icons that break layout
* Fix navigation alignment
* Fix Interoperability text overflow
* Fix responsiveness on scan results page - more changes due to design
updates
* Other minor issues
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - -
Fix #253
Fix #257
Fix #261
Fix #266
Make sure you:
> Fix: Design bug fixes

- src/server/routes/scanner.js
> Fix: prevent unexpected token error

- .github/PULL_REQUEST_TEMPLATE.md
> Updated pull request template to have correct link

- src/hexo/themes/sonarwhal/source/core/css/scan-results.css
Make sure you:
I made the word-wrap `break-word` so that the URL doesn't overflow.
> Fixes #286: URL wraps on mobile

- src/hexo/themes/sonarwhal/layout/partials/home.hbs
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ref https://github.com/sonarwhal/sonarwhal.com/issues/273
Fix #273
Close #273
Make sure you:
> Docs: Shortening home page copy

- src/sonarwhal-theme/source/components/anchor-top/anchor-top.css
Make sure you:
The text on the button was turning purple after being
pressed. Updated CSS so the text stays white.
Fix #369
Close #369
> Fix: Back to Top anchor button contrast

- src/sonarwhal-theme/helper/index.js
- src/sonarwhal-theme/layout/partials/sub-page.hbs
> Fix: Fix the breadcrumb

- helpers/update-content.js
- src/sonarwhal-theme/layout/partials/rules-index.hbs
> Docs: Fix rules index images

- helpers/update-content.js
ref #422
Make sure you:
This PR partially fix the issues #422. I need to do some other changes in sonarwhal.
> Docs: Copy rules images

- src/sonarwhal-theme/helper/index.js
> Fix: Few javascript compatibilities in IE11

- gulpfile.js
- helpers/precompile-hbs.js
- src/sonarwhal-theme/layout/scan.hbs
- src/sonarwhal-theme/source/js/scanner-submit.js
> New: Precompile partial views

- gulpfile.js
- package-lock.json
- package.json
> Fix: Gulp watch task

- src/sonarwhal-theme/source/core/css/type.css
Make sure you:
Makes page heading width larger
Fix #441
Close #441
> Fix: Documentation title lengths

- src/server/routes/scanner.js
- src/webhint-theme/layout/common.ejs
- src/webhint-theme/layout/partials/under-construction.ejs
> Fix: Fix previous default layout behavior

- src/webhint-theme/layout/error.ejs
> Fix: Not found page

- src/server/routes/scanner.js
> Fix: Remove old db fields support

- src/server/routes/scanner.js
> add error to appinsight

- package-lock.json
- package.json
- src/server/routes/scanner.js
> Fix: Date field doesn't show anything

- src/webhint-theme/source/js/scanner-submit.js
> Fix: Update favicon when we receive some result.

- src/webhint-theme/source/core/css/documentation.css
> Fix: detail/summary cursor

- src/server/routes/scanner.js
Before merge this PR, https://github.com/webhintio/online-service/pull/167 has to be merged and deployed.
Make sure you:
> Fix: Add new condition to show queue screen

- src/server/routes/scanner.js
- src/webhint-theme/source/js/scanner-submit.js
Fix #545
This PR needs to wait until https://github.com/webhintio/hint/pull/1424 is merged (no need to wait for a new version to be published)
Make sure you:
> Fix: Show error message when all hints have fail

- helpers/update-content.js
> New: Add new sections to user guide

- helpers/update-content.js
> Fix: Support meta files for hints

- package-lock.json
- package.json
- src/webhint-theme/scripts/custom-renderer.js
`markdown-toc` remove content in some titles when we are generating the id.
Make sure you:
> Fix: Use `uslug` instead of `markdown-toc

- helpers/update-content.js
- helpers/updater.js
- package-lock.json
- src/webhint-theme/scripts/link-filter.js
> Fix: Links to hint documentation in multi-hints index doc

- helpers/update-content.js
- src/webhint-theme/helper/utils.js
> New: Add a landing page for each category

- azure-pipelines.yml
- helpers/update-site.sh
- package.json
Make sure you:
Fix #593
This enables deployment from Azure Websites (🤞).
> Build: Enable deployment from Azure Pipelines

- src/webhint-theme/source/core/css/base.css
- src/webhint-theme/source/core/css/controls.css
- src/webhint-theme/source/core/css/documentation.css
- src/webhint-theme/source/core/css/home.css
- src/webhint-theme/source/core/css/scan-results.css
Make sure you:
Clean up button code and move to a separate universal file. I avoided consolidating scan-results.css button code due to the dependencies two CSS files have on each other at the moment. Also a few other minor updates to CSS code cleanup that were noticeable while going through the CSS files.
Fix #196
Close #196
> Chore: Clean up button CSS code

- _config.yml
> New: Add description for Pitfalls category

- package-lock.json
- src/webhint-theme/source/components/anchor-top/anchor-top.css
- src/webhint-theme/source/core/css/controls.css
- src/webhint-theme/source/core/css/home.css
Make sure you:
Updates to CSS to ensure buttons and hyperlinks all have focus styles as well as updating the focus styles to be more prominent.
Fix #454
> Update and add focus styles for accessibility

- package-lock.json
- src/webhint-theme/source/js/scanner-submit.js
> Fix: Scan results overview padding.

- package-lock.json
- package.json
- src/webhint-theme/scripts/custom-renderer.js
> Fix: Details/summary

- src/webhint-theme/scripts/custom-renderer.js
> Fix: Documentation links in subheaders

- src/webhint-theme/layout/partials/doc.ejs
- src/webhint-theme/layout/partials/header.ejs
- src/webhint-theme/source/components/menu-button/menu-button.js
- src/webhint-theme/source/components/treeview/treeview.js
- src/webhint-theme/source/core/css/navigation.css
- src/webhint-theme/source/js/gdpr.js
- src/webhint-theme/source/js/nav.js
> Fix: A11y reported by aXe with `aria-hidden`

- src/webhint-theme/source/core/css/search-results.css
> Fix: Layout bug with search input

- src/webhint-theme/layout/partials/doc-index.ejs
- src/webhint-theme/source/core/css/documentation.css
Make sure you:
Fix #582 
Re-design docs landing page. 
Added:
h1 heading
Added a link to the Hints to be consistent with the pattern we use across the site which is linking to the contributor guide, linking to the user guide and linking to hints.
> Redesign docs landing page

- README.md
Readme.md has incorrect git repo url and the fetch script should be `update-site` instead of `update-content`
CC @molant
> Docs: Updte Readme.md with correct git url and update script

- _config.yml
- helpers/update-site.js
- helpers/update-site/documentation.js
- package-lock.json
- package.json
- src/webhint-theme/scripts/custom-renderer.js
- src/webhint-theme/source/core/css/highlight.css
> Fix: Code formatting.

- .dependabot/config.yml
- package-lock.json
- package.json
- src/server/routes/scanner.js
> Fix: How to call to the HTML Formatter to work with the latest version

- helpers/update-site/documentation.js
- package-lock.json
- package.json
> Fix: Support Localization metadata in hints to generate docs

- src/webhint-theme/layout/partials/home.ejs
> Fix: Broken links

- helpers/update-site/documentation.js
- src/webhint-theme/layout/partials/hints-category.ejs
> Fix: Category details should use friendly name

- gulpfile.js
- package-lock.json
- package.json
- src/server/routes/scanner.js
- src/webhint-theme/layout/partials/scan-result-container.ejs
- src/webhint-theme/layout/scan.ejs
Before accept this PR, https://github.com/webhintio/hint/pull/2709 needs to be merged and published.
Fix #749
Make sure you:
> Fix: Support localized formatter html

- package.json
> Fix: Website

- helpers/postinstall.js
> Fix: Postinstall script error in deploy

- helpers/update-site.sh
> Fix: Adding helpers to the deploy script

- package-lock.json
- package.json
- src/server/routes/scanner.js
> Fix: Formatter issue after update

- .github/PULL_REQUEST_TEMPLATE.md
Make sure you:
Fixed typo in pull request template.
> Fix: Typo in Pull Request Template

- gulpfile.js
- package.json
> Fix: Error with new Hexo version

- helpers/integration-tests/index.js
- helpers/integration-tests/scanner.js
- package.json
> Fix staging

- package.json
- src/server/routes/scanner.js
- src/webhint-theme/source/js/scanner-submit.js
> Fix: Remove empty categories from the result page

- src/webhint-theme/layout/partials/metas.ejs
Make sure you:
Add required Open Graph properties.
Rel #516
> Fix: Add og:url and og:type

- src/server/routes/scanner.js
> PR: Fix issue with hint count not displaying

- src/webhint-theme/source/js/telemetry/telemetry.js
Updates structure of data submitted to the telemetry API to align with changes from June.
Make sure you:
> Chore: Fix online scanner 28-day activity

- _config.yml
- src/webhint-theme/layout/partials/footer.ejs
- src/webhint-theme/layout/partials/home.ejs
- src/webhint-theme/layout/partials/scan-form.ejs
- src/webhint-theme/layout/partials/scripts.ejs
- src/webhint-theme/source/js/gdpr.js
> Remove GA from website

- src/webhint-theme/helper/utils.js
> Fix: Remove package hint from the section Hints in the documentation

- src/server/index.js
- src/server/routes/search.js
> Fix: Search api

- helpers/update-site.sh
> Fix: Deployment script

- package.json
- src/webhint-theme/helper/utils.js
- src/webhint-theme/layout/partials/doc.ejs
- src/webhint-theme/source/core/css/type.css
Make sure you:
Do not merge at least until Monday, just in case :)
> Chore: Update webhint

- package.json
> Chore: Update webhint packages version
